networks:
  gocanto:
    name: gocanto
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:17.4
    container_name: gocanto-db
    networks:
      - gocanto
    environment:
      POSTGRES_USER: gocanto
      POSTGRES_DB: gocanto_blog
      POSTGRES_PASSWORD: gocanto
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "10M"
    healthcheck:
      timeout: 60s
      interval: 10s
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready --username=gocanto --dbname=gocanto_blog --host=database"]
