# --- .github/workflows/deploy.yml
#     This GitHub Actions workflow automates the deployment of the Go application.
#     It builds the application, then securely deploys the binary and Makefile
#     to a remote VPS and restarts a given supervisor service.

name: VPS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment:
    strategy:
      matrix:
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker with Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env File
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        shell: bash

      - name: Build with Makefile
        run: make build:prod

      - name: Release Artifacts
        run: make build:release
