name: Go Fmt

on: [pull_request]

permissions:
    contents: write

jobs:
    gofmt:
        strategy:
            matrix:
                go-version: [1.24.5]
                os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Run Formatter
              run: gofmt -w -s .

            - name: Commit Changes
              uses: stefanzweifel/git-auto-commit-action@v6.0.1
              with:
                  commit_message: apply coding style fixes
                  commit_options: '--no-verify'
                  file_pattern: .
                  repository: .
                  commit_user_name: GitHub Actions
                  commit_user_email: actions@github.com
                  commit_author: gocanto <gocanto@users.noreply.github.com>
                  branch: ${{ github.head_ref }}
