name: Pkg Tests

on:
  workflow_dispatch:
  pull_request:
    types: [ready_for_review, synchronize, labeled]

jobs:
  pkg-tests:
    if: github.event.pull_request.draft == false || (github.event.action == 'labeled' && github.event.label.name == 'testing')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run pkg tests
        run: |
          go test ./pkg/... -coverprofile=coverage.out
          go tool cover -func=coverage.out | tail -n 1
