name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.x]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v4

      - name: Run unit tests
        run: go test ./pkg/... -coverprofile=coverage.out

      - name: Coverage Report
        run: go tool cover -func=coverage.out
