name: Tests

on:
  pull_request:
    types: [ready_for_review, synchronize, labeled]

jobs:
  test:
    if: github.event.pull_request.draft == false || (github.event.action == 'labeled' && github.event.label.name == 'testing')
    runs-on: ubuntu-latest
    strategy:
        matrix:
          go-version: ['1.24.5']
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run pkg tests
        run: |
          go test -coverpkg=./... ./pkg/... -coverprofile=coverage-pkg.out
          go tool cover -func=coverage-pkg.out | tail -n 1

      - name: Run boost & env tests
        run: |
          go test -coverpkg=./... ./boost ./env -coverprofile=coverage-boost-env.out
          go tool cover -func=coverage-boost-env.out | tail -n 1

      - name: Run handlers tests
        run: |
          go test -coverpkg=./... ./handler/... -coverprofile=coverage-handler.out
          go tool cover -func=coverage-handler.out | tail -n 1

      - name: Run database tests
        run: |
          go test -coverpkg=./... ./database/... -coverprofile=coverage-database.out
          go tool cover -func=coverage-database.out | tail -n 1

      - name: Merge coverage reports
        run: |
          echo "mode: set" > coverage.out
          tail -q -n +2 coverage-*.out >> coverage.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
